config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
    <div class="inner">
    <p class"app-footer"><%= copyright_generator %></p>
    </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="collapse" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 py-4">
                <ul class="list-unstyled">
                    <%= nav_helper 'text-black', 'li'%>
                    <li><%= login_helper "text-black" %></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="navbar navbar-light nav-button shadow">
    <div class="container d-flex justify-content-between">
    <%= link_to "Lynzie J", root_path %>
    <button class= "btn btn-light" "navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
    <p> <%= copyright_generator %></p>
    <p>
    <a href="#">Back to top</a>
    </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
    <div class="container">
        <h1 class="blog-title">Lynzie Blogs Sometimes</h1>
        <p class="lead blog-description">#bloglife</p>
        <span>
        <%= link_to 'Write a New Blog | ', new_blog_path if logged_in?(:site_admin) %>
        </span>

        <span>
        <%= link_to "Topics", topics_path%>
        </span>

    
    </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="collapse" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 py-4">
                <ul class="list-unstyled">
                    <%= nav_helper 'text-black', 'li'%>
                    <li><%= login_helper "text-black" %></li>
                </ul>
            </div>
        </div>
    </div>
</div>


<div class="navbar navbar-light nav-button shadow">
    <div class="container d-flex justify-content-between">
    <%= link_to "Lynzie J", root_path %>
    <button class= "btn btn-light" "navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
    <div class="sidebar-module sidebar-module-inset">
        <h4>About</h4>
        <p>This is a cool blog that I will be full of great stuff eventually</p>
    </div>

    <%= source_helper("alert alert-info blog-sidebar-source")%>

    <div class="sidebar-module">
        <%= source_helper ("alert alert-info") %>
    </div>
    <div class="sidebar-module">
        <h4> Topics </h4>
        <% @side_bar_topics.each do |topic| %>
            <p><%= link_to topic.title, topic_path(topic)%> </p>
        <% end %>
    </div>

    <div class="sidebar-module">
        <h4>Find Me On:</h4>
            <ol class="list-unstyled social-links">
                <li><a href="https://github.com/lynzie-jjohnson"<%=fa_icon "github"%></a></li>
                <li><a href="https://twitter.com/lynziejj"<%=fa_icon "twitter"%></a></li>
                <li><a href="https://www.instagram.com/johnsonlynzie/?hl=en"<%=fa_icon "instagram"%></a></li>
                <li><a href="https://www.linkedin.com/in/lynzie-johnson-005843149"<%=fa_icon "linkedin"%></a></li>
            </ol>
    </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location%>">
      <div><%= link_to "Home", root_path %></div>
      <div><%= link_to "About", about_path %></div>
      <div><%= link_to "Contact", contact_path %></div> 
      <div><%= link_to "Blog", blogs_path %></div> 
      <div><%= link_to "Portfolio", portfolios_path %></div> 
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
    <div class="container">
        <p class="float-right">
        <%= link_to "View All Portfolio Items", portfolios_path %>
            <a href="#">Back to top</a>
        </p>
            <%= copyright_generator %>
            
        </p>
    </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Exciting Stuff</h1>
        <p class="lead text-muted">Super exciting stuff that is going to exsist in 9 weeks!</p>
        <p>
            <%= link_to 'Find Out More About Me!', about_path, class: 'btn bnt-primary'%>
            <%= link_to 'Check Out My Blog!', blogs_path, class: 'btn bnt-secondary'%>

        </p>
    </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 py-4">
                <ul class="list-unstyled">
                    <%= nav_helper 'text-black', 'li'%>
                    <li><%= login_helper "text-black" %></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="navbar navbar-light nav-button shadow">
    <div class="container d-flex justify-content-between">
    <%= link_to "Lynzie J", root_path %>
    <button class= "btn btn-light" "navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    </div>
</div>